using Azure.AI.OpenAI;
using ChatServer.Configuration;
using ChatServer.Services;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Hosting;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Options;
using ModelContextProtocol.Client;
using System.ClientModel;

var builder = WebApplication.CreateBuilder(args);

// Configure URLs
builder.WebHost.UseUrls("http://localhost:5005", "https://localhost:5006");

// Configure Azure OpenAI options
builder.Services
    .AddOptions<AzureOpenAIOptions>()
    .Bind(builder.Configuration.GetSection(AzureOpenAIOptions.SectionName))
    .Validate(o => !string.IsNullOrWhiteSpace(o.Endpoint), "Endpoint missing")
    .Validate(o => !string.IsNullOrWhiteSpace(o.ApiKey), "ApiKey missing")
    .Validate(o => !string.IsNullOrWhiteSpace(o.ModelName), "ModelName missing")
    .ValidateOnStart();

// Configure Chat Client and AI Agents
builder.Services.AddSingleton<IChatClient>(sp => {
    var opts = sp.GetRequiredService<IOptions<AzureOpenAIOptions>>().Value;
    var client = new AzureOpenAIClient(
        new Uri(opts.Endpoint),
        new ApiKeyCredential(opts.ApiKey));
    return client.GetChatClient(opts.ModelName).AsIChatClient();
});

builder.AddAIAgent("VisionAgent", (sp, key) => {
    var chatClient = sp.GetRequiredService<IChatClient>();
    return new ChatClientAgent(
        chatClient,
        name: key,
        instructions: """
                    You are a vision analysis agent. Your task is to analyze images provided by users and extract relevant information that can assist in addressing their queries.
                    Provide detailed descriptions of the images, including any text, objects, or notable features you observe.
                    Do not answer user questions directly nor share any recommendations; instead, focus on analyzing the images.
                    Present your findings clearly and concisely, as this information will be used by other agents to formulate responses to user questions.
                    Format your response in the following way:
                    '
                        User query: [Insert user question here],
                        Image content analysis: [Insert detailed analysis of the image here. If there is no image, put 'No image'.]
                    '
                """
    );
});

// Create an MCP client for the DevExpress endpoint
await using var mcpClient = await McpClient.CreateAsync(
    new HttpClientTransport(new HttpClientTransportOptions
    {
        Endpoint = new Uri("https://api.devexpress.com/mcp/docs")
    })
);
var mcpTools = await mcpClient.ListToolsAsync().ConfigureAwait(false);

builder.AddAIAgent("SupportAgent", (sp, key) => {
    var chatClient = sp.GetRequiredService<IChatClient>();
    return new ChatClientAgent(
        chatClient,
        name: key,
        instructions: """
                    You are a virtual DevExtreme support assistant that helps resolve issues.
                    Use the available tools to find information in the DevExpress documentation and provide accurate answers to users' questions.
                    If you find relevant information, include it in your response with proper citations.
                    Always aim to provide clear, concise, and helpful answers to users' questions.
                    Ask for clarification if a question is ambiguous or lacks sufficient detail.
                """,
        tools: [.. mcpTools.Cast<AITool>()]
    );
});

builder.AddAIAgent("Editor", (sp, key) => {
    var chatClient = sp.GetRequiredService<IChatClient>();
    return new ChatClientAgent(
        chatClient,
        name: key,
        instructions: """
                    You are an editor who refines and enhances the clarity, coherence, and overall quality of responses generated by other agents.
                    Your goal is to ensure that the final output is polished, well-structured, and effectively communicates the intended message to the user.
                """
    );
});

builder.AddWorkflow("VirtualAssistant", (sp, key) => {
    var visionAgent = sp.GetRequiredKeyedService<AIAgent>("VisionAgent");
    var supportAgent = sp.GetRequiredKeyedService<AIAgent>("SupportAgent");
    var editorAgent = sp.GetRequiredKeyedService<AIAgent>("Editor");

    return AgentWorkflowBuilder.BuildSequential(
        workflowName: key,
        agents: [visionAgent, supportAgent, editorAgent]
    );
}).AddAsAIAgent();

// Configure CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowWeb", policy =>
    {
        policy.WithOrigins("http://localhost:5050")
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials();
    });
});

// Configure session
builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(options => {
    options.IdleTimeout = TimeSpan.FromMinutes(15);
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;

    if (builder.Environment.IsDevelopment())
    {
        // Development: Use Lax (doesn't require HTTPS)
        options.Cookie.SameSite = SameSiteMode.Lax;
        options.Cookie.SecurePolicy = CookieSecurePolicy.None;
    }
    else
    {
        // Production: Use None with Secure (requires HTTPS)
        options.Cookie.SameSite = SameSiteMode.None;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
    }
});
builder.Services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
builder.Services.AddTransient<DataService>();

// Add services to the container.

builder.Services
    .AddControllers()
    .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null);

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseCors("AllowWeb");

app.UseSession();

app.UseAuthorization();

app.MapControllers();

app.Run();
